#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
补充更多H3C和锐捷AP型号
"""

import json

# 读取现有数据
with open("/Coze/Drive/友商交换机分析/ap-compare/ap_data.json", "r", encoding="utf-8") as f:
    data = json.load(f)

existing_ids = {p["id"] for p in data["products"]}

additional_products = []

# ============================================================
# 补充H3C型号 (从23增加到约35)
# ============================================================

# WA7600 系列补充
additional_products.append({
    "id": "h3c_wa7636",
    "vendor": "h3c",
    "model_full_name": "H3C WA7636",
    "product_series": "WA7600",
    "form_factor": "indoor-ceiling",
    "tier_level": 1,
    "wifi_gen": "Wi-Fi 7",
    "has_6ghz": True,
    "max_rate_mbps": 11525,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 4,
    "spatial_streams_6g": 2,
    "radio_count": 3,
    "max_users": 500,
    "uplink_port_speed": 10000,
    "uplink_port_count": 2,
    "has_optical_uplink": True,
    "poe_support": "802.3bt",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": 0,
    "operating_temp_max": 50,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置智能天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": True,
    "security_features": ["WPA3", "WIDS/WIPS", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["壁挂", "吸顶"],
    "power_consumption_max": 45,
    "weight_kg": 1.6,
    "dimensions_mm": "240×240×50",
    "typical_scenario": ["高密办公", "高端壁挂场景"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": True,
    "status": "active",
    "release_date": "2025-Q1",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

# WA7500 系列补充
additional_products.append({
    "id": "h3c_wa7539",
    "vendor": "h3c",
    "model_full_name": "H3C WA7539",
    "product_series": "WA7500",
    "form_factor": "indoor-high-density",
    "tier_level": 2,
    "wifi_gen": "Wi-Fi 7",
    "has_6ghz": True,
    "max_rate_mbps": 18670,
    "spatial_streams_2g": 4,
    "spatial_streams_5g": 4,
    "spatial_streams_6g": 4,
    "radio_count": 3,
    "max_users": 800,
    "uplink_port_speed": 10000,
    "uplink_port_count": 2,
    "has_optical_uplink": True,
    "poe_support": "802.3bt",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": 0,
    "operating_temp_max": 50,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置全向天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": True,
    "security_features": ["WPA3", "WIDS/WIPS", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 50,
    "weight_kg": 1.8,
    "dimensions_mm": "250×250×55",
    "typical_scenario": ["高密场馆", "会议中心"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": True,
    "status": "active",
    "release_date": "2024-Q4",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

# WA7200 系列补充
additional_products.append({
    "id": "h3c_wa7232",
    "vendor": "h3c",
    "model_full_name": "H3C WA7232",
    "product_series": "WA7200",
    "form_factor": "indoor-ceiling",
    "tier_level": 3,
    "wifi_gen": "Wi-Fi 7",
    "has_6ghz": True,
    "max_rate_mbps": 6453,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 200,
    "uplink_port_speed": 2500,
    "uplink_port_count": 2,
    "has_optical_uplink": False,
    "poe_support": "802.3af",
    "has_bluetooth": True,
    "has_iot_expansion": False,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": 0,
    "operating_temp_max": 50,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置天线",
    "has_smart_antenna": False,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": True,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 18,
    "weight_kg": 0.65,
    "dimensions_mm": "180×180×35",
    "typical_scenario": ["企业办公", "中小企业"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": True,
    "status": "active",
    "release_date": "2025-Q1",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

additional_products.append({
    "id": "h3c_wa7222f",
    "vendor": "h3c",
    "model_full_name": "H3C WA7222F",
    "product_series": "WA7200",
    "form_factor": "indoor-ceiling",
    "tier_level": 3,
    "wifi_gen": "Wi-Fi 7",
    "has_6ghz": True,
    "max_rate_mbps": 5400,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 150,
    "uplink_port_speed": 2500,
    "uplink_port_count": 1,
    "has_optical_uplink": False,
    "poe_support": "802.3af",
    "has_bluetooth": True,
    "has_iot_expansion": False,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": 0,
    "operating_temp_max": 50,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置天线",
    "has_smart_antenna": False,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": True,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 15,
    "weight_kg": 0.6,
    "dimensions_mm": "170×170×33",
    "typical_scenario": ["金融网点", "中小企业办公"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": True,
    "status": "active",
    "release_date": "2025-Q2",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

# WA6600 补充
additional_products.append({
    "id": "h3c_wa6636",
    "vendor": "h3c",
    "model_full_name": "H3C WA6636",
    "product_series": "WA6600",
    "form_factor": "indoor-high-density",
    "tier_level": 2,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 5950,
    "spatial_streams_2g": 4,
    "spatial_streams_5g": 4,
    "spatial_streams_6g": 0,
    "radio_count": 3,
    "max_users": 400,
    "uplink_port_speed": 10000,
    "uplink_port_count": 3,
    "has_optical_uplink": True,
    "poe_support": "802.3bt",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 55,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置智能天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "WIDS/WIPS", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 48.6,
    "weight_kg": 1.6,
    "dimensions_mm": "240×240×50",
    "typical_scenario": ["高密场馆", "会议中心"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2020-Q4",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

additional_products.append({
    "id": "h3c_wa6638i",
    "vendor": "h3c",
    "model_full_name": "H3C WA6638i",
    "product_series": "WA6600",
    "form_factor": "indoor-high-density",
    "tier_level": 2,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 5950,
    "spatial_streams_2g": 4,
    "spatial_streams_5g": 4,
    "spatial_streams_6g": 0,
    "radio_count": 3,
    "max_users": 500,
    "uplink_port_speed": 10000,
    "uplink_port_count": 2,
    "has_optical_uplink": True,
    "poe_support": "802.3bt",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 55,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置天线",
    "has_smart_antenna": False,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "WIDS/WIPS", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 42,
    "weight_kg": 1.4,
    "dimensions_mm": "220×220×48",
    "typical_scenario": ["高密办公", "高教"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2021-Q1",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

# WA6500 系列补充
additional_products.append({
    "id": "h3c_wa6526",
    "vendor": "h3c",
    "model_full_name": "H3C WA6526",
    "product_series": "WA6500",
    "form_factor": "indoor-ceiling",
    "tier_level": 3,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 2975,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 200,
    "uplink_port_speed": 2500,
    "uplink_port_count": 1,
    "has_optical_uplink": False,
    "poe_support": "802.3af",
    "has_bluetooth": True,
    "has_iot_expansion": False,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 55,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置智能天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 15,
    "weight_kg": 0.6,
    "dimensions_mm": "180×180×32",
    "typical_scenario": ["企业办公", "高教"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2020-Q3",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

additional_products.append({
    "id": "h3c_wa6522",
    "vendor": "h3c",
    "model_full_name": "H3C WA6522",
    "product_series": "WA6500",
    "form_factor": "indoor-ceiling",
    "tier_level": 3,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 1775,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 150,
    "uplink_port_speed": 1000,
    "uplink_port_count": 1,
    "has_optical_uplink": False,
    "poe_support": "802.3af",
    "has_bluetooth": True,
    "has_iot_expansion": False,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 55,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置智能天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 13,
    "weight_kg": 0.5,
    "dimensions_mm": "180×180×32",
    "typical_scenario": ["中小企业办公", "零售"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2020-Q3",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

additional_products.append({
    "id": "h3c_wa6520-hi",
    "vendor": "h3c",
    "model_full_name": "H3C WA6520-HI",
    "product_series": "WA6500",
    "form_factor": "indoor-ceiling",
    "tier_level": 3,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 3550,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 200,
    "uplink_port_speed": 2500,
    "uplink_port_count": 1,
    "has_optical_uplink": True,
    "poe_support": "802.3af",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 55,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置智能天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 16,
    "weight_kg": 0.6,
    "dimensions_mm": "180×180×35",
    "typical_scenario": ["企业办公", "高教"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2021-Q1",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

# WA6300 系列补充
additional_products.append({
    "id": "h3c_wa6338-hi",
    "vendor": "h3c",
    "model_full_name": "H3C WA6338-HI",
    "product_series": "WA6300",
    "form_factor": "indoor-ceiling",
    "tier_level": 4,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 3550,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 3,
    "max_users": 200,
    "uplink_port_speed": 1000,
    "uplink_port_count": 2,
    "has_optical_uplink": False,
    "poe_support": "802.3af",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 55,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置天线",
    "has_smart_antenna": False,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 16,
    "weight_kg": 0.5,
    "dimensions_mm": "170×170×35",
    "typical_scenario": ["企业办公", "高教"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2021-Q2",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

# WA6100 / WA6000 价值级
additional_products.append({
    "id": "h3c_wa6120",
    "vendor": "h3c",
    "model_full_name": "H3C WA6120",
    "product_series": "WA6100",
    "form_factor": "indoor-ceiling",
    "tier_level": 5,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 1775,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 64,
    "uplink_port_speed": 1000,
    "uplink_port_count": 1,
    "has_optical_uplink": False,
    "poe_support": "802.3af",
    "has_bluetooth": False,
    "has_iot_expansion": False,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 55,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置天线",
    "has_smart_antenna": False,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 10,
    "weight_kg": 0.4,
    "dimensions_mm": "150×150×30",
    "typical_scenario": ["SMB办公", "零售", "小型企业"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2021-Q3",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

# 室外型补充
additional_products.append({
    "id": "h3c_wa7220x",
    "vendor": "h3c",
    "model_full_name": "H3C WA7220X",
    "product_series": "WA7200X",
    "form_factor": "outdoor",
    "tier_level": 3,
    "wifi_gen": "Wi-Fi 7",
    "has_6ghz": True,
    "max_rate_mbps": 5400,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 200,
    "uplink_port_speed": 2500,
    "uplink_port_count": 2,
    "has_optical_uplink": True,
    "poe_support": "802.3af",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "IP67",
    "operating_temp_min": -40,
    "operating_temp_max": 65,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置全向天线",
    "has_smart_antenna": False,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": True,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["抱杆", "壁挂"],
    "power_consumption_max": 25,
    "weight_kg": 2.5,
    "dimensions_mm": "220×220×90",
    "typical_scenario": ["园区", "小区", "室外覆盖"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/Default.htm",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": True,
    "status": "active",
    "release_date": "2025-Q1",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

additional_products.append({
    "id": "h3c_wa6320x-g",
    "vendor": "h3c",
    "model_full_name": "H3C WA6320X-G",
    "product_series": "WA6300X",
    "form_factor": "outdoor",
    "tier_level": 4,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 1775,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 100,
    "uplink_port_speed": 1000,
    "uplink_port_count": 1,
    "has_optical_uplink": False,
    "poe_support": "802.3af",
    "has_bluetooth": True,
    "has_iot_expansion": False,
    "distributed_units": 0,
    "protection_rating": "IP67",
    "operating_temp_min": -40,
    "operating_temp_max": 60,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置天线",
    "has_smart_antenna": False,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["抱杆", "壁挂"],
    "power_consumption_max": 15,
    "weight_kg": 2.0,
    "dimensions_mm": "200×200×80",
    "typical_scenario": ["小区", "小型景区"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/Default.htm",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2021-Q2",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

# 面板型补充
additional_products.append({
    "id": "h3c_wa6526h",
    "vendor": "h3c",
    "model_full_name": "H3C WA6526H",
    "product_series": "WA6520H",
    "form_factor": "wall-plate",
    "tier_level": 3,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 5375,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 60,
    "uplink_port_speed": 2500,
    "uplink_port_count": 1,
    "has_optical_uplink": True,
    "poe_support": "802.3af",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 50,
    "wall_plate_downlink_ports": 4,
    "antenna_type": "内置智能天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["86面板嵌入"],
    "power_consumption_max": 15,
    "weight_kg": 0.3,
    "dimensions_mm": "86×86×30",
    "typical_scenario": ["高端酒店", "宿舍", "医院病房"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/Products/Panel_AP/WiFi_6/WA6520H/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2021-Q1",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

additional_products.append({
    "id": "h3c_wa6322h-hi",
    "vendor": "h3c",
    "model_full_name": "H3C WA6322H-HI",
    "product_series": "WA6320H",
    "form_factor": "wall-plate",
    "tier_level": 4,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 2975,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 50,
    "uplink_port_speed": 1000,
    "uplink_port_count": 1,
    "has_optical_uplink": False,
    "poe_support": "802.3af",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 50,
    "wall_plate_downlink_ports": 3,
    "antenna_type": "内置智能天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["86面板嵌入"],
    "power_consumption_max": 13,
    "weight_kg": 0.25,
    "dimensions_mm": "86×86×30",
    "typical_scenario": ["酒店客房", "宿舍"],
    "product_url": "https://www.h3c.com/cn/Products_And_Solution/InterConnect/Products/IP_Wlan/Products/Panel_AP/WiFi_6/WA6320H/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2021-Q1",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "新华三官网"
})

# ============================================================
# 补充锐捷型号 (从24增加到约30)
# ============================================================

additional_products.append({
    "id": "ruijie_rg-ap850-i",
    "vendor": "ruijie",
    "model_full_name": "RG-AP850-I",
    "product_series": "RG-AP850",
    "form_factor": "indoor-ceiling",
    "tier_level": 3,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 3550,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 256,
    "uplink_port_speed": 2500,
    "uplink_port_count": 1,
    "has_optical_uplink": True,
    "poe_support": "802.3at",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 50,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置智能天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "WIDS/WIPS", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 25,
    "weight_kg": 1.2,
    "dimensions_mm": "200×200×45",
    "typical_scenario": ["企业办公", "高教", "医疗"],
    "product_url": "https://www.ruijie.com.cn/cp/wx/",
    "datasheet_url": "",
    "is_hot": True,
    "is_new": False,
    "status": "active",
    "release_date": "2020-Q4",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "锐捷网络官网"
})

additional_products.append({
    "id": "ruijie_rg-ap850-tr",
    "vendor": "ruijie",
    "model_full_name": "RG-AP850(TR)",
    "product_series": "RG-AP850",
    "form_factor": "indoor-high-density",
    "tier_level": 3,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 5375,
    "spatial_streams_2g": 4,
    "spatial_streams_5g": 4,
    "spatial_streams_6g": 0,
    "radio_count": 3,
    "max_users": 300,
    "uplink_port_speed": 2500,
    "uplink_port_count": 2,
    "has_optical_uplink": True,
    "poe_support": "802.3at",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 50,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置智能天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "WIDS/WIPS", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 30,
    "weight_kg": 1.3,
    "dimensions_mm": "210×210×50",
    "typical_scenario": ["三射频高密", "会议中心", "高教"],
    "product_url": "https://www.ruijie.com.cn/cp/wx/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2021-Q2",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "锐捷网络官网"
})

additional_products.append({
    "id": "ruijie_rg-ap820-ar",
    "vendor": "ruijie",
    "model_full_name": "RG-AP820-AR(V3)",
    "product_series": "RG-AP820",
    "form_factor": "indoor-high-density",
    "tier_level": 4,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 3550,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 3,
    "max_users": 200,
    "uplink_port_speed": 2500,
    "uplink_port_count": 1,
    "has_optical_uplink": False,
    "poe_support": "802.3af",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 50,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置智能天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 18,
    "weight_kg": 0.8,
    "dimensions_mm": "190×190×42",
    "typical_scenario": ["高密办公", "高教教室"],
    "product_url": "https://www.ruijie.com.cn/cp/wx/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2021-Q3",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "锐捷网络官网"
})

additional_products.append({
    "id": "ruijie_rg-ap180-l-v3",
    "vendor": "ruijie",
    "model_full_name": "RG-AP180-L(V3)",
    "product_series": "RG-AP180",
    "form_factor": "wall-plate",
    "tier_level": 5,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 1775,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 32,
    "uplink_port_speed": 1000,
    "uplink_port_count": 1,
    "has_optical_uplink": False,
    "poe_support": "802.3af",
    "has_bluetooth": False,
    "has_iot_expansion": False,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 40,
    "wall_plate_downlink_ports": 3,
    "antenna_type": "内置天线",
    "has_smart_antenna": False,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": True,
    "mounting_methods": ["86面板嵌入"],
    "power_consumption_max": 8,
    "weight_kg": 0.15,
    "dimensions_mm": "86×86×28",
    "typical_scenario": ["经济型酒店", "宿舍"],
    "product_url": "https://www.ruijie.com.cn/cp/wx/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2022-Q1",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "锐捷网络官网"
})

additional_products.append({
    "id": "ruijie_rg-ap680-cd",
    "vendor": "ruijie",
    "model_full_name": "RG-AP680-CD(V3)",
    "product_series": "RG-AP680",
    "form_factor": "outdoor",
    "tier_level": 4,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 1775,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 2,
    "spatial_streams_6g": 0,
    "radio_count": 2,
    "max_users": 100,
    "uplink_port_speed": 1000,
    "uplink_port_count": 1,
    "has_optical_uplink": False,
    "poe_support": "802.3af",
    "has_bluetooth": False,
    "has_iot_expansion": False,
    "distributed_units": 0,
    "protection_rating": "IP68",
    "operating_temp_min": -40,
    "operating_temp_max": 65,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置定向天线",
    "has_smart_antenna": False,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["抱杆", "壁挂"],
    "power_consumption_max": 15,
    "weight_kg": 2.0,
    "dimensions_mm": "250×170×60",
    "typical_scenario": ["室外定向覆盖", "网桥", "点对点"],
    "product_url": "https://www.ruijie.com.cn/cp/wx/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2021-Q4",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "锐捷网络官网"
})

additional_products.append({
    "id": "ruijie_rg-ap6920-d",
    "vendor": "ruijie",
    "model_full_name": "RG-AP6920-D",
    "product_series": "RG-AP6900",
    "form_factor": "outdoor",
    "tier_level": 2,
    "wifi_gen": "Wi-Fi 7",
    "has_6ghz": False,
    "max_rate_mbps": 8647,
    "spatial_streams_2g": 2,
    "spatial_streams_5g": 4,
    "spatial_streams_6g": 2,
    "radio_count": 3,
    "max_users": 300,
    "uplink_port_speed": 10000,
    "uplink_port_count": 2,
    "has_optical_uplink": True,
    "poe_support": "802.3at",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "IP68",
    "operating_temp_min": -40,
    "operating_temp_max": 65,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置全向天线",
    "has_smart_antenna": False,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": True,
    "security_features": ["WPA3", "WIDS/WIPS", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["抱杆", "壁挂"],
    "power_consumption_max": 45,
    "weight_kg": 5.0,
    "dimensions_mm": "260×260×110",
    "typical_scenario": ["园区", "广场", "校区"],
    "product_url": "https://www.ruijie.com.cn/cp/wx/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": True,
    "status": "active",
    "release_date": "2025-Q1",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "锐捷网络官网"
})

additional_products.append({
    "id": "ruijie_rg-ap7176-r",
    "vendor": "ruijie",
    "model_full_name": "RG-AP7176-R(V2)",
    "product_series": "RG-AP7100",
    "form_factor": "indoor-high-density",
    "tier_level": 2,
    "wifi_gen": "Wi-Fi 7",
    "has_6ghz": False,
    "max_rate_mbps": 17982,
    "spatial_streams_2g": 4,
    "spatial_streams_5g": 8,
    "spatial_streams_6g": 4,
    "radio_count": 4,
    "max_users": 800,
    "uplink_port_speed": 10000,
    "uplink_port_count": 2,
    "has_optical_uplink": True,
    "poe_support": "802.3bt",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 0,
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 50,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "内置智能天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": True,
    "security_features": ["WPA3", "WIDS/WIPS", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["吸顶", "壁挂"],
    "power_consumption_max": 65,
    "weight_kg": 2.2,
    "dimensions_mm": "250×250×60",
    "typical_scenario": ["超高密场馆", "大型会议中心"],
    "product_url": "https://www.ruijie.com/id-id/products/wireless/indoor-access-points/rg-ap9220",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": True,
    "status": "active",
    "release_date": "2025-Q1",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "锐捷网络官网"
})

additional_products.append({
    "id": "ruijie_rg-am5528-es",
    "vendor": "ruijie",
    "model_full_name": "RG-AM5528(ES) 智分+主机",
    "product_series": "RG-AM5500",
    "form_factor": "distributed",
    "tier_level": 3,
    "wifi_gen": "Wi-Fi 6",
    "has_6ghz": False,
    "max_rate_mbps": 8000,
    "spatial_streams_2g": 48,
    "spatial_streams_5g": 48,
    "spatial_streams_6g": 0,
    "radio_count": 48,
    "max_users": 768,
    "uplink_port_speed": 10000,
    "uplink_port_count": 4,
    "has_optical_uplink": True,
    "poe_support": "none",
    "has_bluetooth": True,
    "has_iot_expansion": True,
    "distributed_units": 24,
    "distributed_unit_model": "RG-MAP852",
    "protection_rating": "",
    "operating_temp_min": -10,
    "operating_temp_max": 50,
    "wall_plate_downlink_ports": 0,
    "antenna_type": "远端单元内置天线",
    "has_smart_antenna": True,
    "mu_mimo": True,
    "ofdma": True,
    "mlo_support": False,
    "security_features": ["WPA3", "WIDS/WIPS", "802.1X"],
    "cloud_management": True,
    "fit_mode": True,
    "fat_mode": False,
    "mounting_methods": ["机架安装"],
    "power_consumption_max": 150,
    "weight_kg": 4.0,
    "dimensions_mm": "442×220×43.6",
    "typical_scenario": ["宿舍", "酒店", "医院"],
    "product_url": "https://www.ruijie.com.cn/cp/wx-zfap-xkap/map852sfmt/",
    "datasheet_url": "",
    "is_hot": False,
    "is_new": False,
    "status": "active",
    "release_date": "2022-Q1",
    "last_updated": "2026-08-14T12:00:00+08:00",
    "data_source": "锐捷网络官网"
})

# 过滤已存在的ID
new_products = [p for p in additional_products if p["id"] not in existing_ids]
print(f"新增型号数: {len(new_products)}")

data["products"].extend(new_products)

# 重新统计
vendor_counts = {
    "huawei": len([p for p in data["products"] if p["vendor"] == "huawei"]),
    "h3c": len([p for p in data["products"] if p["vendor"] == "h3c"]),
    "ruijie": len([p for p in data["products"] if p["vendor"] == "ruijie"])
}

data["metadata"]["total_count"] = len(data["products"])
data["metadata"]["vendor_counts"] = vendor_counts

# 写回文件
with open("/Coze/Drive/友商交换机分析/ap-compare/ap_data.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"总型号数: {data['metadata']['total_count']}")
print(f"华为: {vendor_counts['huawei']}")
print(f"H3C: {vendor_counts['h3c']}")
print(f"锐捷: {vendor_counts['ruijie']}")
